---
title: "ABQ Daily Report"
author: "Connor Whalen, Gabby Commisso, Katie Leslie, Chelsea Wood"
date: "2025-06-10"
output:
  html_document:
    theme: readable
    highlight: textmate
    toc: true
    toc_float: true
    toc_depth: 3
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
# Description
Summary log of leadership and decision activities conducted by leadership team at the University of New Mexico during our 2025 summer CAREER parasite lab work in Albuquerque, New Mexico. 

## Link to Google Spreadsheet
[Lot selection and tracking spreadsheet](https://docs.google.com/spreadsheets/d/1waDMf6cTmtEeaT_14-uCFXRKaHarc8dxyh9Y7yJx9l0/edit?pli=1&gid=486468529#gid=486468529)

# 6/11/25
Connor sent resampling lots and numbers to Chelsea who replaced them in the spreadsheet on 6/12/25. The lots are as follows:
MSB:Fish:5253	Gambusia affinis
MSB:Fish:5247	Hybognathus amarus
MSB:Fish:5803	Hybognathus amarus
MSB:Fish:11156 Pimephales promelas
MSB:Fish:11167	Pimephales promelas
MSB:Fish:1171	Hybognathus amarus
MSB:Fish:1150	Hybognathus amarus
MSB:Fish:3651	Pimephales promelas
MSB:Fish:30386	Gambusia affinis
MSB:Fish:30239	Pimephales promelas
MSB:Fish:19232	Gambusia affinis
MSB:Fish:73766	Hybognathus amarus
MSB:Fish:77030	Hybognathus amarus
MSB:Fish:77021	Hybognathus amarus
MSB:Fish:94735	Pimephales promelas

# 6/12/25
Connor found two more lots that need to be resampled. Went back through the code file specimen_tallies.R and checked for resampling options for both GAMAFF 1068 and HYBAMA 1162. Neither of them are able to be replaced as there are no more available lots in the collection for their respective CI category and years. Connor made note of this in the spreadsheet The lots are as follows:
MSB:Fish:1068	Gambusia affinis
MSB:Fish:1162	Hybognathus amarus

# 6/13/25
Connor found more lots that needed to be resampled. Connor also went through the list of missing lots and has identified the majority of those that were not found initially, though some are still missing. We have 1 lot that needs to be either found or resampled to send in the shipment to Katie, as well as a few other lots that are missing. The list of missing lots is here:
MSB:Fish:7917 Pimephales promelas
MSB:Fish:18794 Pimephales promelas
MSB:Fish:334 Gambusia affinis
MSB:Fish:1122	Hybognathus amarus
MSB:Fish:24944 Hybognathus amarus
MSB:Fish:39103 Hybognathus amarus


### Check at the outset to make sure that we are on track to reach our goals with the lots that we have in hand

# Load required packages
library(googledrive)
library(skimr)
library(lubridate)
library(tidyverse)

# First, bring in all of the meta-data you need to unite with your dissection data

meta_data<-read.csv("data/all_lots_okay_to_dissect.csv")
meta_data$combo<-paste(meta_data$CI,meta_data$decade,sep="_")

# Then bring in the dataset

lots<-read.csv("data/final_lots_2024.12.30_WITH_SHIP_REQUEST_missing_lots_replaced.csv")
length(lots$CatalogNumber)

lots_in_hand <- lots %>%
filter(ready!= "SKIP")

length(lots_in_hand$CatalogNumber)
219-203


# Now merge lot data with meta-data (all.x makes sure that you keep all individual fish from the same lot, even though
# they have the same catalog number).

lots_with_metadata<-merge(lots_in_hand, meta_data, by.x = "CatalogNumber", by.y = "CatalogNumber", all.x = TRUE)
length(lots_with_metadata$CatalogNumber)


# Plot to see where the dissected fish fall

plot(jitter(lots_with_metadata$Latitude.y,30)~jitter(lots_with_metadata$YearCollected.y,5))


# Actual level of replication

lots_actual<-lots_with_metadata %>%
  group_by(ScientificName.x,combo.x) %>%
  summarize(actual = n())

View(lots_actual)

count_up<-lots_with_metadata %>%
  group_by(ScientificName.x) %>%
  summarize(actual = 5*n())
  
  
# Tally up everything that is not being shipped

dissect_here<-lots_with_metadata %>%
filter(SHIP_REQUEST != "x") %>%
  group_by(ScientificName.x) %>%
  summarize(actual = 5*n())
  
sum(dissect_here$actual)


# I checked lots_actual against the database, and it looks like we have pulled everything it is possible to pull!
# The only chance of filling in gaps is finding uncatalogued specimens. I'll take a quick look and see if any of the
# old jars are by chance not catalogued.

# No uncatalogued lots to be found!






### Code for doing daily checks

# The purpose of this script is to allow dissectors to quickly assess levels of replication in each category
# (i.e., before-impact, after-impact, before-control, after-control) during dissections, so that we can 
# adjust lot selection on the fly if need be. We also want to make sure that fish body size range is constant
# across decades, that latitudes sampled in early days are the same as the latitudes sampled later, and that we are
# on track to hit our dissection goals.


# Load required packages
library(googledrive)
library(skimr)
library(lubridate)
library(tidyverse)


# First, bring in all of the meta-data you need to unite with your dissection data

meta_data<-read.csv("data/all_lots_okay_to_dissect.csv")
meta_data$combo<-paste(meta_data$CI,meta_data$decade,sep="_")

View(meta_data)

### HYBAMA

# Download latest file 

hyb_ama_today<-read.csv("data/HYBAMA Data_2025.06.23.csv")
length(hyb_ama_today$CatalogNumber)

# Now merge dissection data with meta-data (all.x makes sure that you keep all individual fish from the same lot, even though
# they have the same catalog number).

hyb_ama_with_metadata<-merge(hyb_ama_today, meta_data, by = "CatalogNumber", all.x = TRUE)
length(hyb_ama_with_metadata$CatalogNumber)

View(hyb_ama_with_metadata)


# Plot to see where the dissected fish fall

plot(jitter(hyb_ama_with_metadata$Latitude,30)~jitter(hyb_ama_with_metadata$YearCollected,5))


# Desired level of replication

hyb_ama_desired<-read.csv(file="data/hyb_ama_goal.csv")
hyb_ama_desired<-hyb_ama_desired[,-1]
colnames(hyb_ama_desired)[2]<-"n_lots_desired"
hyb_ama_desired$individual_fish_desired<-hyb_ama_desired$n_lots_desired*5


# Actual level of replication

hyb_ama_actual<-hyb_ama_with_metadata %>%
  group_by(combo) %>%
  summarize(actual = n())


# Merge desired and actual

hyb_ama_remaining<-merge(hyb_ama_desired, hyb_ama_actual, by.x = "combo", by.y = "combo", all.x = TRUE, all.y = TRUE)


# Calculate how many you have left

hyb_ama_remaining$to_go<-(hyb_ama_remaining$individual_fish_desired-ifelse(is.na(hyb_ama_remaining$actual),0,hyb_ama_remaining$actual))
sum(hyb_ama_remaining$actual,na.rm=T)
sum(hyb_ama_remaining$to_go,na.rm=T)


# Check that body size is invariant through time

summary(glm(hyb_ama_with_metadata$Total_Length_mm~hyb_ama_with_metadata$YearCollected))
plot(hyb_ama_with_metadata$Total_Length_mm~hyb_ama_with_metadata$YearCollected)
summary(glm(hyb_ama_with_metadata$Total_Length_mm~hyb_ama_with_metadata$Latitude))
plot(hyb_ama_with_metadata$Total_Length_mm~hyb_ama_with_metadata$Latitude)


# Create a matrix that shows how many fish you are finishing per day

hyb_ama_dailies<-hyb_ama_with_metadata %>%
  group_by(Dissection_Date) %>%
  summarize(actual = n())



